// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3KUzx8Y7KsqF0xYP0N0RiiuwMPn0bAc',
    appId: '1:909321726896:web:d991ff8c41f4a96b328475',
    messagingSenderId: '909321726896',
    projectId: 'humancare-connect-69b09',
    authDomain: 'humancare-connect-69b09.firebaseapp.com',
    storageBucket: 'humancare-connect-69b09.firebasestorage.app',
    measurementId: 'G-E0E04B63XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAsGVj23BF4A0apHtnsxzdRUJNak6Mork',
    appId: '1:909321726896:android:c74d01297b2bdc24328475',
    messagingSenderId: '909321726896',
    projectId: 'humancare-connect-69b09',
    storageBucket: 'humancare-connect-69b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSQquJxe73TCP3g35R44mcoSGdkj6qcbQ',
    appId: '1:909321726896:ios:6962ac6c4bf5deea328475',
    messagingSenderId: '909321726896',
    projectId: 'humancare-connect-69b09',
    storageBucket: 'humancare-connect-69b09.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSQquJxe73TCP3g35R44mcoSGdkj6qcbQ',
    appId: '1:909321726896:ios:6962ac6c4bf5deea328475',
    messagingSenderId: '909321726896',
    projectId: 'humancare-connect-69b09',
    storageBucket: 'humancare-connect-69b09.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb3KUzx8Y7KsqF0xYP0N0RiiuwMPn0bAc',
    appId: '1:909321726896:web:7f7c66ef4234f528328475',
    messagingSenderId: '909321726896',
    projectId: 'humancare-connect-69b09',
    authDomain: 'humancare-connect-69b09.firebaseapp.com',
    storageBucket: 'humancare-connect-69b09.firebasestorage.app',
    measurementId: 'G-QFLWVXR2S8',
  );
}
